[general]

# Annotate PyTorchGeoNodes (pgn) scenes only
annotate_pgn_only = True

# Base path to SCANnotate Dataset
SCANNOTATE_PATH = /home/sinisa/Projects/SPforSU/ScanNet/ScannotateDataset/
# Folder in SCANNOTATE_PATH where annotated scenes are located
out_folder = annotations

# Base path to ScanNet scans
SCANNET_base_path = /home/sinisa/Projects/SPforSU/ScanNet/data/scans

sam_checkpoint_path = /home/sinisa/Downloads/sam_vit_h_4b8939.pth
sam_model_type = vit_h
use_2d_inst_from_RGB = False
img_height = 480.
img_width = 640.
dataset = ScanNet

# Only generate masks for specific classes
inst_seg_2d_labels_list = ['chair','table','desk','sofa']
;inst_seg_2d_labels_list = ['chair','table','desk','sofa','bookshelf','cabinet']
