num_loops: 3
load_ordered_dv: True
refinement:
    use_refinement: True
    optimize_threshold: 0.0   # This gets replaced anyways
    refine_during_sim: False
    optimize_steps: 50
    optimizer_lr: 0.01
    final_optimization_steps: 100
    optimizer: 'Adam' # 'Adam' or 'SGD' or 'Lion'
    final_optimizer_lr: 0.01
target:
    loss:
        cd_clamp: 0.005 # in m
        fine_loss_thresh: 0.005 # in m
        render_loss_constant: 0.2