population_size: 32
#num_parents: 64
num_offsprings: 64
init_population_size: 100
select_criterion: 'keep_n_best' # 'avg' 'keep_n_best'
remove_bad_decision_values: True
incoming_population_size: 32
init_mutation_rate_offspring: 0.5
init_mutation_rate_param: 0.5
final_mutation_rate_offspring: 0.5
final_mutation_rate_param: 0.5
max_offsprings_per_parent: 10000 # set to high number for no effect
init_mutation_noise: 0.05
final_mutation_noise: 0.05
add_random_individuals_every: 0
num_generations: 20
refine_every_n_generations: 1
#convergence_threshold: 0.00
max_processes_num: 3
load_ordered_dv: True
posterior_tree:
    use_prior_distribution: True
    use_posterior_tree: True
    share_children_nodes: True
refinement:
    use_fast_loss: True
    full_refinement_frequency: 0
    refinement_probability: 0.2
    optimize_threshold: 0.0   # This gets replaced anyways
    optimize_steps: 50
    optimizer_lr: 0.01
    optimizer: 'Adam' # 'Adam' or 'SGD' or 'Lion'
    final_optimization_steps: 500
    final_optimizer_lr: 0.01
target:
    loss:
        cd_clamp: 0.005 # in m
        fine_loss_thresh: 0.005 # in m
        render_loss_constant: 0.2
logging:
    log_time: False
    log_steps: True
    log_iters: True
