scannet_processed_path: '/path/to/ScanNet/data/scans/'
scannet_ply_path: '/path/to/ScanNet/data/scans/'
scannotate_dataset_path: '/path/to/ScannotateDataset'
scannotate_masks_path: '/path/to/ScannotateDataset/Scannotate_2d_masks'
