scannet_processed_path: '/home/sinisa/Projects/SPforSU/ScanNet/data/scans/'
scannet_ply_path: '/home/sinisa/Projects/SPforSU/ScanNet/data/scans/'
scannotate_dataset_path: '/home/sinisa/Projects/SPforSU/ScanNet/ScannotateDataset'
scannotate_masks_path: '/home/sinisa/Projects/SPforSU/ScanNet/ScannotateDataset/Scannotate_2d_masks'